import { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  schema: process.env.ALKEMIO_GRAPHQL_ENDPOINT || 'http://localhost:3000/graphql',
  documents: ['src/graphql/queries/**/*.graphql', 'src/graphql/fragments/**/*.graphql'],
  generates: {
    'src/graphql/generated/alkemio-schema.ts': {
      plugins: [
        {
          add: {
            content: `/* eslint-disable */\n/* Auto-generated by GraphQL Codegen — do not edit */`,
          },
        },
        'typescript',
        'typescript-resolvers',
        'typescript-operations',
      ],
      config: {
        skipTypename: true,
        maybeValue: 'T | undefined',
        scalars: {
          NameID: 'string',
          UUID: 'string',
          DID: 'string',
          DateTime: 'Date',
          JSON: 'string',
        },
      },
    },
    'src/graphql/generated/graphql.ts': {
      preset: 'import-types',
      presetConfig: {
        typesPath: './alkemio-schema',
        importTypesNamespace: 'SchemaTypes',
      },
      plugins: [
        {
          add: {
            content: `/* eslint-disable */\n/* Auto-generated by GraphQL Codegen — do not edit */`,
          },
        },
        'typescript',
        'typescript-resolvers',
        'typescript-operations',
        'typescript-graphql-request',
      ],
      config: {
        maybeValue: 'T | undefined',
        rawRequest: true,
        preResolveTypes: true,
        skipTypename: true,
        enumsAsTypes: true,
        customHeaders: true,
        scalars: {
          NameID: 'string',
          UUID: 'string',
          DID: 'string',
          DateTime: 'Date',
          JSON: 'string',
          Headers: 'Record<string, string>',
        },
      },
    },
  },
};

export default config;
