// AUTO-GENERATED by server/scripts/generate-nl-geo.mts — do not edit by hand.
// Per-province basemaps, rendered like the whole-NL map (see MapOverlay/ForceGraph).

export type ProvinceRegion = 'groningen' | 'fryslan' | 'drenthe' | 'overijssel' | 'flevoland' | 'gelderland' | 'utrecht' | 'noord-holland' | 'zuid-holland' | 'zeeland' | 'noord-brabant' | 'limburg';

export interface ProvinceBasemap {
  /** CBS province statcode, e.g. "PV22" — matches the GeoJSON feature statcode. */
  code: string;
  name: string;
  url: string;
  center: [number, number];
  scale: number;
}

export const PROVINCE_BASEMAPS: Record<ProvinceRegion, ProvinceBasemap> = {
  'groningen': { code: 'PV20', name: "Groningen", url: '/maps/provinces/groningen.geojson', center: [6.7014, 53.1961], scale: 23165 },
  'fryslan': { code: 'PV21', name: "Fryslân", url: '/maps/provinces/fryslan.geojson', center: [5.6363, 53.1591], scale: 15402 },
  'drenthe': { code: 'PV22', name: "Drenthe", url: '/maps/provinces/drenthe.geojson', center: [6.6063, 52.908], scale: 25054 },
  'overijssel': { code: 'PV23', name: "Overijssel", url: '/maps/provinces/overijssel.geojson', center: [6.4291, 52.4862], scale: 18936 },
  'flevoland': { code: 'PV24', name: "Flevoland", url: '/maps/provinces/flevoland.geojson', center: [5.5683, 52.5483], scale: 27351 },
  'gelderland': { code: 'PV25', name: "Gelderland", url: '/maps/provinces/gelderland.geojson', center: [5.9134, 52.1278], scale: 13256 },
  'utrecht': { code: 'PV26', name: "Utrecht", url: '/maps/provinces/utrecht.geojson', center: [5.2097, 52.0805], scale: 29184 },
  'noord-holland': { code: 'PV27', name: "Noord-Holland", url: '/maps/provinces/noord-holland.geojson', center: [4.9113, 52.6756], scale: 17327 },
  'zuid-holland': { code: 'PV28', name: "Zuid-Holland", url: '/maps/provinces/zuid-holland.geojson', center: [4.435, 51.9914], scale: 20434 },
  'zeeland': { code: 'PV29', name: "Zeeland", url: '/maps/provinces/zeeland.geojson', center: [3.8179, 51.4793], scale: 26523 },
  'noord-brabant': { code: 'PV30', name: "Noord-Brabant", url: '/maps/provinces/noord-brabant.geojson', center: [5.1191, 51.5258], scale: 13119 },
  'limburg': { code: 'PV31', name: "Limburg", url: '/maps/provinces/limburg.geojson', center: [5.8964, 51.2645], scale: 17178 },
};
