/**
 * VNG snapshot registry loader.
 *
 * Loads the committed gemeente/theme snapshot (generated by
 * scripts/generate-vng-snapshot.mts from the vng-gemeente-delers vault) and exposes
 * lookups used to (a) identify gemeente organisations for the show/hide toggle and
 * (b) resolve GemeenteDelers initiative Callout tags to gemeente org nameIDs / theme
 * nodes. See specs/016-vng-frontend/contracts/snapshot-registry.md (FR-032/033/040/041).
 *
 * Public reference data only; loaded once and cached.
 */
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

export interface RegistryMunicipality {
  slug: string;
  title: string;
  alkemioNameId: string | null;
  cbsCode: string | null;
}
export interface RegistryTheme {
  slug: string;
  title: string;
  priorLabels: string[];
}
export interface RegistryMeta {
  generatedFrom: string;
  municipalityCount: number;
  themeCount: number;
  initiativeCountAtGeneration: number;
  programme: { name: string; years: string; sourceUrl: string };
}

/** A Dutch province (the 12 provincies). See server/src/data/nl/provinces.json. */
export interface RegistryProvince {
  /** CBS statcode, e.g. "PV22" — matches the basemap GeoJSON feature statcode. */
  code: string;
  /** ascii kebab slug, e.g. "drenthe" — the province map region id. */
  slug: string;
  name: string;
}

/**
 * Province + population facts for one municipality (server/src/data/nl/
 * municipality-facts.json, joined on cbsCode). For the two Belgian entries
 * (Brugge, Gent) there is no province and country is 'BE'.
 */
export interface MunicipalityInfo {
  cbsCode: string | null;
  /** ISO 3166-1 alpha-2 — 'NL' for the 342 gemeenten, 'BE' for Brugge/Gent. */
  country: 'NL' | 'BE';
  provinceCode: string | null;
  provinceName: string | null;
  /** Inhabitants (CBS), or null for non-NL municipalities. */
  population: number | null;
}

/** A gemeente found in free text. */
export interface GemeenteMatch {
  nameId: string;
  /** Canonical gemeente name (the snapshot title, e.g. "Groningen"). */
  title: string;
}

export interface VngRegistry {
  /** Is this organisation nameID a known gemeente? (FR-032/035) */
  isGemeenteNameId(nameId: string | null | undefined): boolean;
  /** Resolve a Callout tag (e.g. "Groningen") to a gemeente org nameID (e.g. "gemeente-groningen"). */
  resolveGemeenteByTag(tag: string): string | null;
  /** Resolve a Callout tag (e.g. "Energietransitie") to a canonical theme. */
  resolveThemeByTag(tag: string): RegistryTheme | null;
  /**
   * Find every gemeente whose name appears in free text (e.g. a GD initiative's
   * description) as a whole word, case-insensitively. Distinct, sorted by name.
   */
  findGemeentesInText(text: string | null | undefined): GemeenteMatch[];
  /** Every known gemeente org nameID. */
  gemeenteNameIds(): string[];
  /** The 12 Dutch provinces, ordered by CBS code. */
  provinces(): RegistryProvince[];
  /**
   * Province + population for a gemeente organisation nameID (e.g.
   * "gemeente-groningen"), or null when the nameID is not a known gemeente.
   */
  municipalityInfoByNameId(nameId: string | null | undefined): MunicipalityInfo | null;
  meta(): RegistryMeta;
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const DATA_DIRS = [
  join(import.meta.dirname, '../data/vng'), // tsx dev (src/) and prod after build copy (dist/)
  join(import.meta.dirname, '../../src/data/vng'), // dist/ fallback to source tree
  join(process.cwd(), 'src/data/vng'),
];

function resolveDataDir(): string {
  for (const d of DATA_DIRS) {
    if (existsSync(join(d, 'meta.json'))) return d;
  }
  throw new Error(
    `VNG snapshot data not found. Run \`pnpm -C server run gen:vng-snapshot\`. Searched: ${DATA_DIRS.join(', ')}`,
  );
}

// Netherlands geography facts (provinces + population), generated by
// scripts/generate-nl-geo.mts. Sits alongside the VNG snapshot; same copy-to-dist.
const NL_DATA_DIRS = [
  join(import.meta.dirname, '../data/nl'),
  join(import.meta.dirname, '../../src/data/nl'),
  join(process.cwd(), 'src/data/nl'),
];

function resolveNlDataDir(): string {
  for (const d of NL_DATA_DIRS) {
    if (existsSync(join(d, 'provinces.json'))) return d;
  }
  throw new Error(
    `NL geography data not found. Run \`pnpm -C server run gen:nl-geo\`. Searched: ${NL_DATA_DIRS.join(', ')}`,
  );
}

function readJson<T>(dir: string, file: string): T {
  return JSON.parse(readFileSync(join(dir, file), 'utf8')) as T;
}

/** Case-fold + collapse whitespace for tag matching. */
function norm(value: string): string {
  return value.trim().toLowerCase().replace(/\s+/g, ' ');
}

let cached: VngRegistry | null = null;

export function loadVngRegistry(): VngRegistry {
  if (cached) return cached;

  const dir = resolveDataDir();
  const municipalities = readJson<RegistryMunicipality[]>(dir, 'municipalities.json');
  const themes = readJson<RegistryTheme[]>(dir, 'themes.json');
  const meta = readJson<RegistryMeta>(dir, 'meta.json');

  // NL geography facts — province + population, joined to municipalities on cbsCode.
  const nlDir = resolveNlDataDir();
  const provinces = readJson<RegistryProvince[]>(nlDir, 'provinces.json');
  const factsByCbs = readJson<
    Record<string, { provinceCode: string; provinceName: string; population: number }>
  >(nlDir, 'municipality-facts.json');
  const infoByNameId = new Map<string, MunicipalityInfo>();
  for (const m of municipalities) {
    if (!m.alkemioNameId) continue;
    const f = m.cbsCode ? factsByCbs[m.cbsCode] : undefined;
    infoByNameId.set(m.alkemioNameId, {
      cbsCode: m.cbsCode,
      // The only municipalities without a CBS code in the snapshot are Belgian.
      country: m.cbsCode ? 'NL' : 'BE',
      provinceCode: f?.provinceCode ?? null,
      provinceName: f?.provinceName ?? null,
      population: f?.population ?? null,
    });
  }

  const gemeenteNameIdSet = new Set<string>();
  const tagToGemeenteNameId = new Map<string, string>();
  // Precompiled whole-word matchers for free-text gemeente detection (description).
  // Longer names first so "Bergen op Zoom" wins over "Bergen" when both could match.
  const textMatchers: { nameId: string; title: string; re: RegExp }[] = [];
  for (const m of municipalities) {
    if (!m.alkemioNameId) continue;
    gemeenteNameIdSet.add(m.alkemioNameId);
    tagToGemeenteNameId.set(norm(m.title), m.alkemioNameId);
    textMatchers.push({
      nameId: m.alkemioNameId,
      title: m.title,
      // Bounded by a non-letter/digit (or string edge) so "Best" doesn't match "Bestuur".
      re: new RegExp(`(^|[^\\p{L}\\p{N}])${escapeRegExp(norm(m.title))}([^\\p{L}\\p{N}]|$)`, 'u'),
    });
  }
  textMatchers.sort((a, b) => b.title.length - a.title.length);

  const tagToTheme = new Map<string, RegistryTheme>();
  for (const t of themes) {
    tagToTheme.set(norm(t.title), t);
    for (const prior of t.priorLabels) tagToTheme.set(norm(prior), t);
  }

  cached = {
    isGemeenteNameId: (nameId) => !!nameId && gemeenteNameIdSet.has(nameId),
    resolveGemeenteByTag: (tag) => tagToGemeenteNameId.get(norm(tag)) ?? null,
    resolveThemeByTag: (tag) => tagToTheme.get(norm(tag)) ?? null,
    findGemeentesInText: (text) => {
      if (!text) return [];
      // Strip HTML/markdown but keep line breaks so the anchor line can be isolated.
      const clean = text
        .replace(/<br\s*\/?>/gi, '\n')
        .replace(/<\/(p|div|li|h[1-6])>/gi, '\n')
        .replace(/<[^>]+>/g, ' ')
        .replace(/[*_]{1,3}/g, '');
      // GD descriptions name the municipality after "Deelnemende gemeente(n):"
      // (see design). Anchor on that line for precision; if it's absent, fall back
      // to scanning the whole description.
      const anchor = clean.match(/deelnemende\s+gemeente[n]?\s*:\s*([^\n\r]*)/i);
      const hay = norm(anchor ? anchor[1] : clean);
      const seen = new Map<string, GemeenteMatch>();
      for (const m of textMatchers) {
        if (!seen.has(m.nameId) && m.re.test(hay)) seen.set(m.nameId, { nameId: m.nameId, title: m.title });
      }
      return [...seen.values()].sort((a, b) => a.title.localeCompare(b.title));
    },
    gemeenteNameIds: () => [...gemeenteNameIdSet],
    provinces: () => provinces,
    municipalityInfoByNameId: (nameId) => (nameId ? infoByNameId.get(nameId) ?? null : null),
    meta: () => meta,
  };
  return cached;
}
