import { describe, it, expect } from 'vitest';
import { loadVngRegistry } from './vng-registry.js';

// Province + population enrichment (feature: provinces). Reads the committed
// NL geography snapshot (server/src/data/nl), generated by scripts/generate-nl-geo.mts.
describe('vng-registry NL geography', () => {
  const registry = loadVngRegistry();

  it('exposes the 12 Dutch provinces, ordered by CBS code', () => {
    const provinces = registry.provinces();
    expect(provinces).toHaveLength(12);
    expect(provinces.map((p) => p.code)).toEqual([
      'PV20', 'PV21', 'PV22', 'PV23', 'PV24', 'PV25',
      'PV26', 'PV27', 'PV28', 'PV29', 'PV30', 'PV31',
    ]);
    expect(provinces.find((p) => p.code === 'PV22')).toMatchObject({
      slug: 'drenthe',
      name: 'Drenthe',
    });
  });

  it('resolves a gemeente nameID to its province and population', () => {
    const info = registry.municipalityInfoByNameId('gemeente-groningen');
    expect(info).toMatchObject({ country: 'NL', provinceCode: 'PV20', provinceName: 'Groningen' });
    expect(info?.population).toBeGreaterThan(0);
  });

  it('returns null for a non-gemeente nameID', () => {
    expect(registry.municipalityInfoByNameId('not-a-gemeente')).toBeNull();
    expect(registry.municipalityInfoByNameId(null)).toBeNull();
  });

  it('every known gemeente has a resolvable province and population', () => {
    for (const nameId of registry.gemeenteNameIds()) {
      const info = registry.municipalityInfoByNameId(nameId);
      expect(info, nameId).not.toBeNull();
      // The gemeente registry only contains NL municipalities (Belgian entries carry
      // no nameID), so every one resolves to a province with a positive population.
      expect(info!.provinceCode, nameId).toMatch(/^PV\d\d$/);
      expect(info!.population, nameId).toBeGreaterThan(0);
    }
  });
});
